apiVersion: v2
type: application
version: 3.0.3
appVersion: "3.0.3"
name: nutanix-csi-snapshot
description: Snapshot components required for CSI snapshotting and not specific to any CSI driver
home: https://github.com/nutanix/helm
maintainers:
- name: nutanix-cloud-native-bot
  email: cloudnative@nutanix.com
icon: https://avatars2.githubusercontent.com/u/6165865?s=200&v=4
keywords:
  - Nutanix
  - Storage
  - Snapshot
  - SnapshotClass
  - RedHat
  - CentOS
  - Ubuntu
annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - Update Snapshot Controller to 3.0.3
  artifacthub.io/links: |
    - name: Kubernetes CSI Developer Documentation
      url: https://kubernetes-csi.github.io/docs/
  artifacthub.io/maintainers: |
    - name: Nutanix Cloud Native Team
      email: cloudnative@nutanix.com
