# https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    app: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-cluster-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: cert-manager
rules:
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "create", "patch"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["certificates.k8s.io"]
    resources: 
      - "certificatesigningrequests/status"
      - "certificatesigningrequests/approval"
      - "signers"
    verbs: ["update", "approve"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "patch"]
  - apiGroups: [""] 
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-cluster-role
subjects:
  - kind: ServiceAccount
    name: cert-manager-service-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cert-manager-setup
  namespace: {{ .Release.Namespace }}
  labels:
    app: cert-manager
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
    spec:
      serviceAccountName: cert-manager-service-account
      containers:
      - name: metadata-cert-setup
        image: {{ .Values.certmanager.image }}
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "snapshot-validation-service"
          - "--webhook"
          - "validation-webhook.snapshot.storage.k8s.io"
          - "--secret"
          - "snapshot-validation-secret"
          - "--namespace"
          - "{{ .Release.Namespace }}"
          - "--webhook-kind"
          - "ValidatingWebhookConfiguration"
      restartPolicy: Never
  backoffLimit: 1
